apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::844709390076:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::844709390076:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DHXQG2E6462R
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-16T11:41:28Z" 
  name: aws-auth
  namespace: kube-system
  resourceVersion: "188173"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 26e983c4-b86a-4890-a330-5c217fa0ea03
